source 'https://rubygems.org'
ruby '2.7.2'

gem 'activesupport'
gem 'curb'
gem 'dotenv'
gem 'jwt'
gem 'rest-client'
gem 'sinatra'

group :development do
  gem 'pry'
  gem 'rerun'
  gem 'terminal-notifier'
end
